# Generated by Django 4.2.1 on 2023-05-11 06:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_id_alter_customer_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
    ]
