# Generated by Django 4.1.7 on 2023-03-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('description', models.JSONField(blank=True, null=True)),
                ('lft', models.IntegerField()),
                ('rght', models.IntegerField()),
                ('tree_id', models.IntegerField()),
                ('level', models.IntegerField()),
                ('background_image', models.CharField(blank=True, max_length=100, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=300, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=70, null=True)),
                ('background_image_alt', models.CharField(max_length=128)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('private_metadata', models.JSONField(blank=True, null=True)),
                ('description_plaintext', models.TextField()),
            ],
            options={
                'db_table': 'product_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=300, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=70, null=True)),
                ('charge_taxes', models.BooleanField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('private_metadata', models.JSONField(blank=True, null=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('description_plaintext', models.TextField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('search_document', models.TextField()),
                ('characteristics', models.JSONField(blank=True, null=True)),
                ('in_discount', models.BooleanField()),
                ('is_recommended', models.BooleanField()),
            ],
            options={
                'db_table': 'product_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductProducttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('has_variants', models.BooleanField()),
                ('is_shipping_required', models.BooleanField()),
                ('weight', models.FloatField()),
                ('is_digital', models.BooleanField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('private_metadata', models.JSONField(blank=True, null=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('kind', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'product_producttype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductProductvariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('track_inventory', models.BooleanField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('private_metadata', models.JSONField(blank=True, null=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('is_preorder', models.BooleanField()),
                ('preorder_end_date', models.DateTimeField(blank=True, null=True)),
                ('preorder_global_threshold', models.IntegerField(blank=True, null=True)),
                ('quantity_limit_per_customer', models.IntegerField(blank=True, null=True)),
                ('in_discount', models.BooleanField()),
            ],
            options={
                'db_table': 'product_productvariant',
                'managed': False,
            },
        ),
    ]
