# Generated by Django 4.1.7 on 2023-03-10 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authpermission',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='accountaddress',
            name='city_area',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='accountaddress',
            name='country_area',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='accountaddress',
            name='street_address_2',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='accountcustomernote',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accountcustomernote',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountcustomernote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.accountuser'),
        ),
        migrations.AlterField(
            model_name='accountstaffnotificationrecipient',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accountstaffnotificationrecipient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.accountuser'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountuseraddresses',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accountaddress'),
        ),
        migrations.AlterField(
            model_name='accountuseraddresses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accountuser'),
        ),
        migrations.AlterField(
            model_name='accountusergroups',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='accountusergroups',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accountuser'),
        ),
        migrations.AlterField(
            model_name='accountuseruserpermissions',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='accountuseruserpermissions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.accountuser'),
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
    ]
